version: '3.8'

services:
  api_dev:
    build:
      context: .
      target: development
    environment:
      - NODE_ENV=development
      - DB_HOST=db_dev
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - DB_DATABASE=nest_app_dev
      - DB_SYNCHRONIZE=true
    depends_on:
      db_dev:
        condition: service_healthy
    command: sh -c 'npm run migration:run && npm run start:dev'
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules

  db_dev:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=nest_app_dev
    ports:
      - '3306:3306'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10

  db_prod:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=nest_app_prod
    ports:
      - '3307:3306'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10

  api_prod:
    build:
      context: .
      target: production
    environment:
      - NODE_ENV=production
      - DB_HOST=db_prod
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - DB_DATABASE=nest_app_prod
    depends_on:
      db_prod:
        condition: service_healthy
    command: sh -c 'npm run migration:run && npm run start:prod'
    ports:
      - '3001:3000'
