version: '3.8'

services:
  api_dev:
    build:
      context: .
      target: development
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_SYNCHRONIZE=${DB_SYNCHRONIZE}
    depends_on:
      db_dev:
        condition: service_healthy
    command: sh -c 'npm run migration:run && npm run pm2:dev'
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    volumes:
      - .:/app
      - /app/node_modules

  db_dev:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    ports:
      - '3306:3306'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 5s
      retries: 10

  api_prod:
    build:
      context: .
      target: production
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_SYNCHRONIZE=${DB_SYNCHRONIZE}
    depends_on:
      db_dev:
        condition: service_healthy
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    volumes:
      - .:/app
      - /app/node_modules
