version: '3.8'

services:
  api_prod:
    build:
      context: .
      target: production
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_SYNCHRONIZE=${DB_SYNCHRONIZE}
    depends_on:
      db_prod:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    volumes:
      - .:/app
      - /app/node_modules

  redis:
    image: redis:7.0.11-alpine
    ports:
      - '${REDIS_PORT}:6379'
    command: redis-server --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 2s
      timeout: 1s
      retries: 5

  db_prod:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    ports:
      - '${DB_PORT}:3306'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 1s
      retries: 10
      interval: 2s
